global using Xunit;
global using Environment = Lururen.Core.EnviromentSystem.Environment;
global using Lururen.Core.CommandSystem;
global using Lururen.Core.EventSystem;
global using Lururen.Core.App;
global using Lururen.Core.Common;
global using Lururen.Core.EntitySystem;
global using Lururen.Networking.Common;
global using Lururen.Networking.Common.Commands;
global using Lururen.Networking.Common.Protocol;
global using Lururen.Networking.Common.ServerMessages;
global using Lururen.Networking.SimpleSocketBus;