global using Lururen.Client;
global using Lururen.Client.Protocol;
global using Lururen.Client.SocketNetworking;
global using Lururen.Common.Networking.Messages;
global using Lururen.Common.Types;
global using Lururen.Server.App;
global using Lururen.Server.Commands;
global using Lururen.Server.CommandSystem;
global using Lururen.Server.EntitySystem;
global using Lururen.Server.SocketNetworking;
global using Lururen.Common.EventSystem;
global using Lururen.Server.EventSystem;
global using Xunit;
global using Environment = Lururen.Server.EnviromentSystem.Environment;