global using Lururen.Client.Core;
global using Lururen.Client.Networking.Protocol;
global using Lururen.Client.Networking.SocketNetworking;
global using Lururen.Common.Networking.Messages;
global using Lururen.Common.Types;
global using Lururen.Server.Core.App;
global using Lururen.Server.Core.CommandSystem;
global using Lururen.Server.Core.EntitySystem;
global using Lururen.Server.Core.ResourceLoader;
global using Lururen.Server.Core.ResourceLoader.DllResourceLoader;
global using Lururen.Server.Networking.Commands;
global using Lururen.Server.Networking.SocketNetworking;
global using Xunit;
global using Environment = Lururen.Server.Core.EnviromentSystem.Environment;